-- public.user_auth_userprofile definition

-- Drop table

-- DROP TABLE user_auth_userprofile;

CREATE TABLE user_auth_userprofile (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	phone_number varchar(10) NULL,
	date_of_birth date NULL,
	country varchar(25) NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	user_id int4 NOT NULL,
	CONSTRAINT user_auth_userprofile_pkey PRIMARY KEY (id),
	CONSTRAINT user_auth_userprofile_user_id_key UNIQUE (user_id)
);
CREATE INDEX user_auth_userprofile_created_by_id_a8c95af7 ON public.user_auth_userprofile USING btree (created_by_id);
CREATE INDEX user_auth_userprofile_modified_by_id_dfe363bd ON public.user_auth_userprofile USING btree (modified_by_id);


-- public.user_auth_userprofile foreign keys

ALTER TABLE public.user_auth_userprofile ADD CONSTRAINT user_auth_userprofile_created_by_id_a8c95af7_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.user_auth_userprofile ADD CONSTRAINT user_auth_userprofile_modified_by_id_dfe363bd_fk_auth_user_id FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.user_auth_userprofile ADD CONSTRAINT user_auth_userprofile_user_id_50430fe4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;