-- public.transactions_transaction definition

-- Drop table

-- DROP TABLE transactions_transaction;

CREATE TABLE transactions_transaction (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	transaction_type_id int8 NOT NULL,
	amount numeric(10, 2) NOT NULL,
	account_id int8 NOT NULL,
	note varchar(255) NULL,
	transaction_date timestamptz NOT NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	category_id int8 NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_transaction_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_transaction_account_id_322da003 ON public.transactions_transaction USING btree (account_id);
CREATE INDEX transactions_transaction_category_id_c06a92e3 ON public.transactions_transaction USING btree (category_id);
CREATE INDEX transactions_transaction_created_by_id_8e7e5eaa ON public.transactions_transaction USING btree (created_by_id);
CREATE INDEX transactions_transaction_modified_by_id_d5367567 ON public.transactions_transaction USING btree (modified_by_id);
CREATE INDEX transactions_transaction_transaction_type_id_7fb404b1 ON public.transactions_transaction USING btree (transaction_type_id);


-- public.transactions_transaction foreign keys

ALTER TABLE public.transactions_transaction ADD CONSTRAINT fk_accounts FOREIGN KEY (account_id) REFERENCES transactions_accounts(id);
ALTER TABLE public.transactions_transaction ADD CONSTRAINT transactions_transac_account_id_322da003_fk_transacti FOREIGN KEY (account_id) REFERENCES transactions_accounts(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transaction ADD CONSTRAINT transactions_transac_category_id_c06a92e3_fk_transacti FOREIGN KEY (category_id) REFERENCES transactions_transactioncategories(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transaction ADD CONSTRAINT transactions_transac_modified_by_id_d5367567_fk_auth_user FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transaction ADD CONSTRAINT transactions_transac_transaction_type_id_7fb404b1_fk_transacti FOREIGN KEY (transaction_type_id) REFERENCES transactions_transactiontypes(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transaction ADD CONSTRAINT transactions_transaction_created_by_id_8e7e5eaa_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;