-- public.transactions_transactioncategories definition

-- Drop table

-- DROP TABLE transactions_transactioncategories;

CREATE TABLE transactions_transactioncategories (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	category_name varchar(50) NOT NULL,
	category_type_id int8 NOT NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_transaction_category_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_transactioncategories_category_type_id_dcb8887a ON public.transactions_transactioncategories USING btree (category_type_id);
CREATE INDEX transactions_transactioncategories_created_by_id_6c567c7f ON public.transactions_transactioncategories USING btree (created_by_id);
CREATE INDEX transactions_transactioncategories_modified_by_id_e2a38100 ON public.transactions_transactioncategories USING btree (modified_by_id);


-- public.transactions_transactioncategories foreign keys

ALTER TABLE public.transactions_transactioncategories ADD CONSTRAINT fk_categorytypes FOREIGN KEY (category_type_id) REFERENCES transactions_transactiontypes(id);
ALTER TABLE public.transactions_transactioncategories ADD CONSTRAINT transactions_transac_category_type_id_dcb8887a_fk_transacti FOREIGN KEY (category_type_id) REFERENCES transactions_transactiontypes(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transactioncategories ADD CONSTRAINT transactions_transac_created_by_id_6c567c7f_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transactioncategories ADD CONSTRAINT transactions_transac_modified_by_id_e2a38100_fk_auth_user FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;