-- public.transactions_transfer definition

-- Drop table

-- DROP TABLE transactions_transfer;

CREATE TABLE transactions_transfer (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(10, 2) NOT NULL,
	transaction_date timestamptz NOT NULL,
	note varchar(255) NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	from_account_id int8 NOT NULL,
	to_account_id int8 NOT NULL,
	transaction_type_id int8 NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_transfer_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_transfer_created_by_id_013ed6b5 ON public.transactions_transfer USING btree (created_by_id);
CREATE INDEX transactions_transfer_from_account_id_ea2bcc11 ON public.transactions_transfer USING btree (from_account_id);
CREATE INDEX transactions_transfer_modified_by_id_40c8cc69 ON public.transactions_transfer USING btree (modified_by_id);
CREATE INDEX transactions_transfer_to_account_id_ea81853f ON public.transactions_transfer USING btree (to_account_id);
CREATE INDEX transactions_transfer_transaction_type_id_6df29dbc ON public.transactions_transfer USING btree (transaction_type_id);


-- public.transactions_transfer foreign keys

ALTER TABLE public.transactions_transfer ADD CONSTRAINT transactions_transfe_from_account_id_ea2bcc11_fk_transacti FOREIGN KEY (from_account_id) REFERENCES transactions_accounts(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transfer ADD CONSTRAINT transactions_transfe_to_account_id_ea81853f_fk_transacti FOREIGN KEY (to_account_id) REFERENCES transactions_accounts(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transfer ADD CONSTRAINT transactions_transfe_transaction_type_id_6df29dbc_fk_transacti FOREIGN KEY (transaction_type_id) REFERENCES transactions_transactiontypes(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transfer ADD CONSTRAINT transactions_transfer_created_by_id_013ed6b5_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transfer ADD CONSTRAINT transactions_transfer_modified_by_id_40c8cc69_fk_auth_user_id FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;