-- public.transactions_accountgroups definition

-- Drop table

-- DROP TABLE transactions_accountgroups;

CREATE TABLE transactions_accountgroups (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(50) NOT NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_accountgroups_name_key UNIQUE (name),
	CONSTRAINT transactions_accountgroups_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_accountgroups_created_by_id_ef13e6e7 ON public.transactions_accountgroups USING btree (created_by_id);
CREATE INDEX transactions_accountgroups_modified_by_id_1cc8cc32 ON public.transactions_accountgroups USING btree (modified_by_id);
CREATE INDEX transactions_accountgroups_name_146cf717_like ON public.transactions_accountgroups USING btree (name varchar_pattern_ops);


-- public.transactions_accountgroups foreign keys

ALTER TABLE public.transactions_accountgroups ADD CONSTRAINT transactions_account_created_by_id_ef13e6e7_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_accountgroups ADD CONSTRAINT transactions_account_modified_by_id_1cc8cc32_fk_auth_user FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;