-- public.transactions_transactiontypes definition

-- Drop table

-- DROP TABLE transactions_transactiontypes;

CREATE TABLE transactions_transactiontypes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(50) NOT NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_transactiontypes_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_transactiontypes_created_by_id_760d8bac ON public.transactions_transactiontypes USING btree (created_by_id);
CREATE INDEX transactions_transactiontypes_modified_by_id_d75e1376 ON public.transactions_transactiontypes USING btree (modified_by_id);


-- public.transactions_transactiontypes foreign keys

ALTER TABLE public.transactions_transactiontypes ADD CONSTRAINT transactions_transac_created_by_id_760d8bac_fk_auth_user FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_transactiontypes ADD CONSTRAINT transactions_transac_modified_by_id_d75e1376_fk_auth_user FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;