-- public.transactions_budget definition

-- Drop table

-- DROP TABLE transactions_budget;

CREATE TABLE transactions_budget (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	amount numeric(10, 2) NOT NULL,
	note varchar(255) NULL,
	"month" int4 NOT NULL,
	"year" int4 NOT NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	category_id int8 NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_budget_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_budget_category_id_4de27e34 ON public.transactions_budget USING btree (category_id);
CREATE INDEX transactions_budget_created_by_id_741003c0 ON public.transactions_budget USING btree (created_by_id);
CREATE INDEX transactions_budget_modified_by_id_e8ad9d73 ON public.transactions_budget USING btree (modified_by_id);


-- public.transactions_budget foreign keys

ALTER TABLE public.transactions_budget ADD CONSTRAINT transactions_budget_category_id_4de27e34_fk_transacti FOREIGN KEY (category_id) REFERENCES transactions_transactioncategories(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_budget ADD CONSTRAINT transactions_budget_created_by_id_741003c0_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_budget ADD CONSTRAINT transactions_budget_modified_by_id_e8ad9d73_fk_auth_user_id FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;