-- public.transactions_accounts definition

-- Drop table

-- DROP TABLE transactions_accounts;

CREATE TABLE transactions_accounts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(50) NOT NULL,
	amount numeric(10, 2) NOT NULL,
	note varchar(255) NULL,
	created_at timestamptz NOT NULL,
	modified_at timestamptz NOT NULL,
	group_id int8 NOT NULL,
	created_by_id int4 NOT NULL,
	modified_by_id int4 NULL,
	CONSTRAINT transactions_accounts_name_key UNIQUE (name),
	CONSTRAINT transactions_accounts_pkey PRIMARY KEY (id)
);
CREATE INDEX transactions_accounts_created_by_id_53d16b23 ON public.transactions_accounts USING btree (created_by_id);
CREATE INDEX transactions_accounts_group_id_4651486d ON public.transactions_accounts USING btree (group_id);
CREATE INDEX transactions_accounts_modified_by_id_475083eb ON public.transactions_accounts USING btree (modified_by_id);
CREATE INDEX transactions_accounts_name_f4febcdd_like ON public.transactions_accounts USING btree (name varchar_pattern_ops);


-- public.transactions_accounts foreign keys

ALTER TABLE public.transactions_accounts ADD CONSTRAINT transactions_account_group_id_4651486d_fk_transacti FOREIGN KEY (group_id) REFERENCES transactions_accountgroups(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_accounts ADD CONSTRAINT transactions_accounts_created_by_id_53d16b23_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.transactions_accounts ADD CONSTRAINT transactions_accounts_modified_by_id_475083eb_fk_auth_user_id FOREIGN KEY (modified_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;