# Generated by Django 5.2 on 2025-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction_Category',
            new_name='TransactionCategories',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_account', 'Bank Account'), ('card', 'Card')], max_length=30),
        ),
    ]
