# Generated by Django 5.2 on 2025-07-10 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transaction_category_transactioncategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactioncategories',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
