# Generated by Django 5.2 on 2025-07-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategories',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontypes'),
        ),
    ]
