# Generated by Django 5.2 on 2025-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncategories',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
