# Generated by Django 5.2 on 2025-07-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
