# Generated by Django 5.2 on 2025-07-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='modifed_at',
            new_name='modified_at',
        ),
    ]
