# Generated by Django 5.2 on 2025-07-26 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_rename_modifed_at_budget_modified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroups',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_group_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountgroups',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_group_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounts',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
