# Generated by Django 5.2 on 2025-07-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_alter_accountgroups_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactiontypes',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
