# Generated by Django 5.2 on 2025-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_alter_transaction_note_alter_transactiontypes_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
