# Generated by Django 5.2 on 2025-07-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_accounts_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
